# 开启 mybatis 驼峰标识
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.clh.seckill.mapper
  configuration:
    map-underscore-to-camel-case: true
spring:
  # ----数据源配置----
  datasource:
    url: jdbc:mysql://localhost:3306/hobo-seckill?serverTimezone=Asia/Shanghai&useAffectedRows=true
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # ----下面为连接池的补充设置，应用到上面所有数据源中----
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 1
    maxActive: 50
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: false
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    #spring.datasource.maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    #spring.datasource.filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    filters: stat
    maxOpenPreparedStatements: 20
    # 合并多个DruidDataSource的监控数据
    #spring.datasource.useGlobalDataSourceStat: true

  #-----Rabbitmq配置-----
  rabbitmq:
    host: 192.168.16.106
    port: 5672
    username:
    password:
    virtual-host: /
    listener.simple.concurrency:  10
    listener.simple.max-concurrency:  10
    listener.simple.prefetch:
    listener.simple.auto-startup: true
    listener.simple.default-requeue-rejected:  true
    template.retry.enabled: true
    template.retry.initial-interval: 1000
    template.retry.max-attempts: 3
    template.retry.max-interval: 10000
    template.retry.multiplier: 1.0
  # ----开启mvc接收restful风格的请求----
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  # -----配置邮箱----------------
  mail:
    host: smtp.qq.com
    username: longhuahobo@foxmail.com
    password:
    port: 465
    properties:
      mail:
        # SMTP服务
        smtp:
          ssl:
            enable: true
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
  #启动aop配置
  aop:
    auto: true
# ----Redis配置----
redis:
#    host: 192.168.16.248
  host: localhost
  port: 6379
  timeout: 10
  # password:
  poolMaxTotal: 1000
  poolMaxIdle: 500
  poolMaxWait: 3
#  sentinel: 47.115.1.148:26379
#  sentinel: 192.168.16.248:26379
# 自定义变量
customize:
  sender: